// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Central Firebase config selector
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'FirebaseOptions not configured for this platform.',
        );
    }
  }

  // ================= WEB =================
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUT8EOnO0vWZyjlu7faSBelLb0wrE_YU4',
    appId: '1:780175935349:web:5d58839ef9a294fb81753c',
    messagingSenderId: '780175935349',
    projectId: 'lobos-trucking',
    authDomain: 'lobos-trucking.firebaseapp.com',
    storageBucket: 'lobos-trucking.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX', // 🔥 optional but recommended
  );

  // ================= ANDROID =================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIROdOfyqQqo2cshMBlqor01Dqdzeo5_4',
    appId: '1:780175935349:android:8001a81322db80e981753c',
    messagingSenderId: '780175935349',
    projectId: 'lobos-trucking',
    storageBucket: 'lobos-trucking.firebasestorage.app',
  );

  // ================= IOS =================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiT9y07HL2I5hncFVjnq4a2JDdHrkpaM8',
    appId: '1:780175935349:ios:b928f09b5af2eab381753c',
    messagingSenderId: '780175935349',
    projectId: 'lobos-trucking',
    storageBucket: 'lobos-trucking.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp', // ⚠️ change later
  );

  // ================= MACOS =================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiT9y07HL2I5hncFVjnq4a2JDdHrkpaM8',
    appId: '1:780175935349:ios:b928f09b5af2eab381753c',
    messagingSenderId: '780175935349',
    projectId: 'lobos-trucking',
    storageBucket: 'lobos-trucking.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  // ================= WINDOWS =================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUT8EOnO0vWZyjlu7faSBelLb0wrE_YU4',
    appId: '1:780175935349:web:e07154ba893d39d581753c',
    messagingSenderId: '780175935349',
    projectId: 'lobos-trucking',
    authDomain: 'lobos-trucking.firebaseapp.com',
    storageBucket: 'lobos-trucking.firebasestorage.app',
  );
}
