// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUT8EOnO0vWZyjlu7faSBelLb0wrE_YU4',
    appId: '1:780175935349:web:5d58839ef9a294fb81753c',
    messagingSenderId: '780175935349',
    projectId: 'lobos-trucking',
    authDomain: 'lobos-trucking.firebaseapp.com',
    storageBucket: 'lobos-trucking.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIROdOfyqQqo2cshMBlqor01Dqdzeo5_4',
    appId: '1:780175935349:android:8001a81322db80e981753c',
    messagingSenderId: '780175935349',
    projectId: 'lobos-trucking',
    storageBucket: 'lobos-trucking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiT9y07HL2I5hncFVjnq4a2JDdHrkpaM8',
    appId: '1:780175935349:ios:b928f09b5af2eab381753c',
    messagingSenderId: '780175935349',
    projectId: 'lobos-trucking',
    storageBucket: 'lobos-trucking.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiT9y07HL2I5hncFVjnq4a2JDdHrkpaM8',
    appId: '1:780175935349:ios:b928f09b5af2eab381753c',
    messagingSenderId: '780175935349',
    projectId: 'lobos-trucking',
    storageBucket: 'lobos-trucking.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUT8EOnO0vWZyjlu7faSBelLb0wrE_YU4',
    appId: '1:780175935349:web:e07154ba893d39d581753c',
    messagingSenderId: '780175935349',
    projectId: 'lobos-trucking',
    authDomain: 'lobos-trucking.firebaseapp.com',
    storageBucket: 'lobos-trucking.firebasestorage.app',
  );
}
